[package]
name = "mc-net"
description = "Connection management and session lifecycle (Solaris)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
load-bench = ["mc-script/lua-runtime"]

[dependencies]
arc-swap = { workspace = true }
mc-data = { path = "../mc-data" }
mc-entity = { path = "../mc-entity" }
mc-extension = { path = "../mc-extension" }
mc-nbt = { path = "../mc-nbt" }
mc-physics = { path = "../mc-physics" }
mc-protocol = { path = "../mc-protocol" }
mc-script = { path = "../mc-script" }
mc-world = { path = "../mc-world" }
bytes = { workspace = true }
fd-lock = { workspace = true }
flate2 = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
md-5 = { workspace = true }
crc32fast = { workspace = true }
aes = { workspace = true }
cfb8 = { workspace = true }
rsa = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
num-bigint = { workspace = true }
reqwest = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
mc-entity = { path = "../mc-entity" }
mc-script = { path = "../mc-script", features = ["lua-runtime"] }
tokio = { workspace = true, features = ["test-util"] }
tempfile = "3"
