[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.94"
license = "MIT OR Apache-2.0"
authors = ["Solaris contributors"]
repository = "https://github.com/example/solaris"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
thiserror = "2"
bytes = "1"
uuid = { version = "1", features = ["serde"] }
flate2 = "1"
lz4_flex = "0.11"
md-5 = "0.10"
proptest = "1"
bevy_ecs = { version = "0.18.1", default-features = false, features = ["std"] }
bytemuck = "1"
wide = "1.5"
mlua = { version = "0.12", default-features = false, features = ["lua54", "vendored"] }
rayon = "1"
crc32fast = "1"
aes = "0.9"
cfb8 = "0.9"
rsa = "0.9"
sha1 = "0.10"
num-bigint = "0.4"
reqwest = { version = "0.13", default-features = false, features = ["query", "rustls"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
