//! P3 resident and resident-order acceptance through one real component and one
//! real world.
//!
//! The component is the repository's own example plugin, built to
//! `wasm32-unknown-unknown` and encoded as a component exactly the way a published
//! package is; the world is a real directory the server opens, saves and reads
//! back, generated by the world's own terrain generator. Two packages of that
//! component run: the owner that holds the resident, and an observer that never
//! does. A real client logs in over the wire and runs the fixture's `resident` root
//! one action at a time, and it runs the observer's `resident-fence` root with the
//! owner's own handle.
//!
//! The settlement profile the owner reserves a site from is the server's own
//! deployed profile: the catalog this test writes beside the component is the
//! authored catalog of a settlement package, declared with the two features the
//! profile needs, so core's discovery validates it and installs the real runtime
//! over the live world - the same path a deployed settlement package takes. Its
//! home blueprint anchors its own point of interest on the column the building is
//! grounded on, so the cell a resident materialises in is the terrain's own
//! surface rather than a spot this test guessed at.
//!
//! The sequence proves, through the owners' own typed answers and the world's own
//! files:
//!
//! * a site listing names an authored site and a free home point of interest with
//!   the cells it stands on, and the reservation that cell answers with a spawn
//!   site token the fixture never derived;
//! * the spawn materialises the server's own villager there: the answer is a
//!   resident snapshot with a handle keyed to this plugin, and it is the only
//!   answer that creates one - a refused spawn hands its reservation back;
//! * a point-of-interest binding commits at the revision the spawn answered, a
//!   binding at the revision that preceded it is refused `stale-revision` with the
//!   binding untouched, and the next binding commits at the revision the refusal
//!   did not move;
//! * a claim of the very villager the spawn materialised, by that entity's own
//!   stable uuid and at the revision the committed binding answered, is answered
//!   with the same resident this plugin holds, and a claim of it at the revision
//!   that preceded the binding is refused `stale-revision` with nothing written;
//! * a haul of an item the worker does not hold pauses `missing_input` and moves
//!   nothing; after a real owned-inventory transfer puts one emerald in its carry,
//!   the same haul commits exactly that item into its equipment and reports the
//!   real change; a work revision that already moved is refused with nothing
//!   applied, and a cancellation answers the revision its record now holds;
//! * a follow order commits with the member applied and a formation slot, an order
//!   at the revision that preceded it is refused as a `blocked` batch whose member
//!   detail is `stale-revision`, and the cancellation commits against the member
//!   list;
//! * the observer's four asks for the owner's resident are refused by the owners'
//!   own reasons - `forbidden` for the point-of-interest call, `not_found` for the
//!   work call, the same `blocked` batch with its per-member detail for the order,
//!   and `stale-revision` for a claim naming a revision only the plugin that holds
//!   the record may name - and the owner's resident still commits a binding at the
//!   revision it held, which is what makes those refusals mean nothing was written;
//! * a demobilisation answers `demobilizing` with its own typed reason and keeps
//!   the handle, and the gear the worker was holding is still on its canonical
//!   slot afterwards - read back through the owned-inventory owner, not from a
//!   value the fixture remembered;
//! * the save path's own player file holds one emerald fewer than it started with,
//!   because the withdrawal really moved one into the resident's carry.
//!
//! A second, non-network case pins the capability boundary: the very record the
//! fixture sends converts under a manifest that declares `persistent_residents`
//! and is refused by *name* under one that does not.

// Reuse the host tests' component builder.
#[path = "../../mc-plugin-host/tests/fixture/mod.rs"]
mod fixture;

use std::collections::{BTreeMap, HashSet};
use std::io::{Read, Write};
use std::net::SocketAddr;
use std::num::NonZeroUsize;
use std::path::Path;
use std::sync::Arc;
use std::time::Duration;

use bytes::Bytes;
use mc_nbt::Tag;
use mc_plugin_host::bindings::solaris::plugin::commands::Command as WireCommand;
use mc_plugin_host::bindings::solaris::plugin::domain_operations::{
    DomainOperation, OperationRequest,
};
use mc_plugin_host::bindings::solaris::plugin::residents::{ResidentClaim, ResidentOperation};
use mc_plugin_host::{
    AdapterError, CommandBatch, DeploymentConfig, DiscoveryMode, HostQueues, HostServices,
    LogLevel, NoSessions, PlayerSessions, PluginHost, PluginLimits, discover,
    start_deployment_with, to_script_batch,
};
use mc_protocol::packets::Packet;
use mc_protocol::packets::play::{
    ClientboundCommands, ClientboundKeepAlive, ClientboundSystemChat, ConfirmTeleportation,
    LevelChunkWithLight, ServerboundChatCommand, ServerboundKeepAlive, ServerboundPlayerLoaded,
    SynchronizePlayerPosition,
};
use mc_script::{CommandCapabilities, ScriptPluginManifest};
use mc_test_harness::client::Client;
use tokio::sync::mpsc::{UnboundedReceiver, UnboundedSender};

/// The package that owns the resident: the id the fixture's own storage is keyed
/// by.
const OWNER: &str = "resident-compat";
/// The package that owns no resident and asks for the owner's.
const OBSERVER: &str = "resident-observer";
/// The namespace the fixture's authored blueprints use. Core derives the catalog
/// namespace from the files themselves, so a deployed catalog is always the one
/// the author wrote, whichever package ships it.
const CATALOG_NAMESPACE: &str = OWNER;

/// The login name of the fixture's one player. Offline mode derives the uuid from
/// it, which is also the name of that player's durable file.
const PLAYER: &str = "Steward";

/// The item the world's player file gives the player and the withdrawal moves into
/// the resident's carry.
const EMERALD_ITEM: &str = "minecraft:emerald";
/// The main-inventory slot the world's player file fills.
const EMERALD_SLOT: u8 = 9;
/// How many emeralds the world's player file gives the player: one withdrawal plus
/// what the save path must still hold.
const SEED_EMERALDS: i32 = 4;

/// The line the fixture logs from `init`, which is what this test waits for before
/// it sends the first action.
const READY: &str = "P3_RES ready";
/// The marker every concluded step is reported under, and the prefix a step that
/// could not be concluded is logged under.
const MARKER: &str = "P3_RES ";
const UNEXPECTED: &str = "P3_RES_UNEXPECTED";

/// The points of interest the fixture binds: the default triple, and the second
/// binding that replaces two of them with one unbound.
const HOME_POI: &str = "res-home";
const WORK_POI: &str = "res-work";
const MEETING_POI: &str = "res-meeting";
const SECOND_HOME_POI: &str = "res-home-2";
const SECOND_MEETING_POI: &str = "res-meeting-2";
const ABSENT: &str = "none";

/// How many times one candidate may answer `unloaded` before this test treats it
/// as a stall: the teleport's own chunk load is asynchronous, so the first attempt
/// after it may still find the cell unreadable.
const UNLOADED_RETRIES: usize = 8;

/// The owner package's manifest: the `resident` root, the events it reads, and the
/// capabilities its operations need - the resident family, its work and order
/// families, the settlement sites it reserves from, the staged construction and
/// authored settlement catalog it owns, the owned-inventory transfers it withdraws
/// with, and the teleport that walks the player to the site. Every
/// feature-capability is required as well, which is what core reads to install the
/// real settlement runtime over the catalog this package ships.
const MANIFEST: &str = r#"
id = "resident-compat"
name = "Resident Compat"
version = "0.1.0"
api = "0.7.0"
events = ["player.left"]
player_commands = ["resident"]
capabilities = ["persistent_residents", "resident_work", "resident_orders", "world_sites", "structure_operations", "inventory_transfers", "player_teleport"]
required_features = ["persistent_residents", "resident_work", "resident_orders", "world_sites", "structure_operations", "inventory_transfers"]
"#;

/// What tells the owner's instance which mode to run.
const CONFIG: &str = "mode = \"resident-operations\"\n";

/// The observer package: the same component under its own id, with its own root
/// and the same resident capabilities, so a refusal it receives is the owner's and
/// not the capability boundary's.
const OBSERVER_MANIFEST: &str = r#"
id = "resident-observer"
name = "Resident Observer"
version = "0.1.0"
api = "0.7.0"
player_commands = ["resident-fence"]
capabilities = ["persistent_residents", "resident_work", "resident_orders"]
required_features = ["persistent_residents", "resident_work", "resident_orders"]
"#;

/// What tells the observer's instance which role to run.
const OBSERVER_CONFIG: &str = "mode = \"resident-operations\"\nrole = \"observer\"\n";

/// How long one action may spend on its real round trips before this test calls it
/// stalled. Nothing here sleeps: the wait ends on the fixture's own line.
const ACTION_TIMEOUT: Duration = Duration::from_secs(30);
/// How long the join may take to publish the manifest's readiness.
const WIRE_TIMEOUT: Duration = Duration::from_secs(10);

/// One package a run deploys: the directory it is written to, its manifest and the
/// configuration its instance reads.
struct Package {
    id: &'static str,
    manifest: &'static str,
    config: &'static str,
}

/// One log line a component guest asked its host to record.
struct LogLine {
    plugin: String,
    /// Whether the guest logged it at error level. The fixture reports a step it
    /// could not conclude that way, so an error line means that step did not
    /// answer.
    error: bool,
    message: String,
}

/// The host-services implementation this test hands the component host: the
/// guest's diagnostics land in this test's own channel instead of a global
/// subscriber, so this binary never touches process-wide tracing state.
struct RecordingLog {
    id: String,
    lines: UnboundedSender<LogLine>,
}

impl HostServices for RecordingLog {
    fn log(&mut self, level: LogLevel, message: &str) {
        let _ = self.lines.send(LogLine {
            plugin: self.id.clone(),
            error: matches!(level, LogLevel::Error),
            message: message.to_owned(),
        });
    }

    fn plugin_id(&self) -> &str {
        &self.id
    }
}

/// The component host's view of this server's live sessions. The fixture addresses
/// its markers to the stable identity, and only the server knows which session that
/// identity holds right now, so this is the production wiring's own pass-through.
struct ServerSessions(mc_net::PlayerSessionsHandle);

impl PlayerSessions for ServerSessions {
    fn session_of(&self, player: &str) -> Option<u64> {
        self.0.session_of(player)
    }
}

/// The immutable registries every run of this test binds with, built from the
/// embedded required data so the test needs no `data/vanilla` sidecar.
struct Registries {
    data: Arc<mc_data::VanillaData>,
    blocks: Arc<mc_world::BlockRegistry>,
    items: Arc<mc_data::items::ItemRegistry>,
    tags: Arc<mc_data::tags::TagsData>,
    recipes: Arc<Vec<mc_data::recipes::Recipe>>,
    loot: Arc<mc_data::loot::LootTables>,
    item_facts: Arc<mc_data::item_components::ItemFactsTable>,
    block_facts: Arc<mc_data::block_facts::BlockFactsTable>,
    entity_types: Arc<mc_data::entity_types::EntityTypeRegistry>,
}

impl Registries {
    fn new() -> Self {
        let block_report = mc_data::blocks::solaris_required_blocks_report();
        let items = Arc::new(mc_data::items::solaris_required_items());
        let tags = Arc::new(mc_data::tags::solaris_required_item_tags(&items));
        let blocks = Arc::new(
            mc_world::BlockRegistry::from_report(&block_report).expect("required block registry"),
        );
        Self {
            data: Arc::new(mc_data::solaris_required_data()),
            blocks,
            tags,
            recipes: Arc::new(mc_data::recipes::solaris_required_recipes()),
            loot: Arc::new(mc_data::loot::builtin().clone()),
            item_facts: Arc::new(mc_data::item_components::solaris_required_item_facts()),
            block_facts: Arc::new(mc_data::block_facts::BlockFactsTable::from_blocks_report(
                &block_report,
            )),
            entity_types: Arc::new(mc_data::entity_types::solaris_required_entity_types()),
            items,
        }
    }
}

/// One running component server: a real host over the packages a test writes to
/// disk - one of which ships the authored settlement catalog - and a real server
/// bound on the world that test opened.
struct Running {
    /// The directory the packages were discovered from. It stays alive for as long
    /// as the host runs, because that is what the host was started from and where
    /// core reads the owner's settlement catalog from.
    _deployment: tempfile::TempDir,
    address: SocketAddr,
    save: mc_net::SaveHandle,
    shutdown: mc_net::ShutdownHandle,
    log: UnboundedReceiver<LogLine>,
    host: PluginHost,
    server: tokio::task::JoinHandle<std::io::Result<()>>,
}

impl Running {
    async fn start(registries: &Registries, world_dir: &Path, packages: &[Package]) -> Self {
        let deployment = tempfile::tempdir().expect("component deployment directory");
        for package in packages {
            let directory = deployment.path().join(package.id);
            std::fs::create_dir_all(&directory).expect("component package directory");
            std::fs::write(directory.join("plugin.toml"), package.manifest)
                .expect("component manifest");
            std::fs::write(directory.join("plugin.wasm"), fixture::component_bytes())
                .expect("component artifact");
            std::fs::write(directory.join("config.toml"), package.config)
                .expect("component config");
            if package.id == OWNER {
                // The owner package is the settlement profile owner: the authored
                // catalog is deployed next to the manifest that declares the
                // profile, so core discovers it from the deployed packages the
                // host publishes and not from a value this test injected.
                write_catalog(&directory);
            }
        }

        let limits = PluginLimits::default();
        let config = DeploymentConfig {
            root: deployment.path().to_path_buf(),
            mode: DiscoveryMode::Strict,
            expected: packages
                .iter()
                .map(|package| package.id.to_owned())
                .collect(),
            grants: BTreeMap::from([
                (
                    OWNER.to_owned(),
                    vec![
                        "persistent_residents".to_owned(),
                        "resident_work".to_owned(),
                        "resident_orders".to_owned(),
                        "world_sites".to_owned(),
                        "structure_operations".to_owned(),
                        "inventory_transfers".to_owned(),
                        "player_teleport".to_owned(),
                    ],
                ),
                (
                    OBSERVER.to_owned(),
                    vec![
                        "persistent_residents".to_owned(),
                        "resident_work".to_owned(),
                        "resident_orders".to_owned(),
                    ],
                ),
            ]),
            require_grants: true,
            precommit_hooks: Vec::new(),
        };
        let discovered = discover(&config, &limits)
            .expect("the component packages are discovered")
            .into_packages();

        let (lines, log) = tokio::sync::mpsc::unbounded_channel();
        let sessions = mc_net::PlayerSessionsHandle::new();
        let host = start_deployment_with(
            discovered,
            limits,
            HostQueues::default(),
            Arc::new(ServerSessions(sessions.clone())),
            move |id: &str| RecordingLog {
                id: id.to_owned(),
                lines: lines.clone(),
            },
        )
        .expect("the component host starts");

        let boundary = host.boundary().clone();

        let shutdown = mc_net::ShutdownHandle::default();
        let config = server_config(
            registries,
            open_world(world_dir, registries),
            &shutdown,
            "resident acceptance",
        );
        let bound = mc_net::bind_with_scripts(config, boundary.clone())
            .await
            .expect("bind the component server");
        // The host resolves a marker's player through this handle, so a plugin's
        // chat line reaches the connection that holds that identity right now.
        bound.register_player_sessions(&sessions);
        let save = bound.save_handle();
        let address = bound.local_addr().expect("component server address");
        let server = tokio::spawn(async move { bound.serve().await });

        Self {
            _deployment: deployment,
            address,
            save,
            shutdown,
            log,
            host,
            server,
        }
    }

    /// Stop the server and its host, and answer the lines the guests logged.
    async fn stop(mut self) -> Vec<LogLine> {
        self.shutdown.request();
        let server = self.server;
        tokio::time::timeout(Duration::from_secs(30), server)
            .await
            .expect("the component server shutdown timed out")
            .expect("the component server task")
            .expect("the component server result");
        let host = self.host;
        let _counters = tokio::task::spawn_blocking(move || host.stop())
            .await
            .expect("component host stop task");
        let mut lines = Vec::new();
        while let Ok(line) = self.log.try_recv() {
            lines.push(line);
        }
        lines
    }
}

/// Everything a run observed while it drove its client: the chat lines the guests
/// published, in the order this test read them.
#[derive(Default)]
struct Journal {
    chats: Vec<String>,
    next_reply: usize,
    /// The chunks the client has actually received data for, keyed by their
    /// coordinates: the publication a refused-unloaded spawn waits for.
    chunks: HashSet<(i32, i32)>,
}

#[tokio::test]
async fn one_component_takes_a_real_resident_through_its_whole_used_surface() {
    let world = tempfile::tempdir().expect("one temporary persistent world");
    std::fs::create_dir_all(world.path().join("region")).expect("world region directory");
    let registries = Registries::new();
    // The world's own durable player file, before the server opens the world: the
    // player arrives with four emeralds, one of which the withdrawal moves.
    seed_player_state(world.path());

    let mut running = Running::start(
        &registries,
        world.path(),
        &[
            Package {
                id: OWNER,
                manifest: MANIFEST,
                config: CONFIG,
            },
            Package {
                id: OBSERVER,
                manifest: OBSERVER_MANIFEST,
                config: OBSERVER_CONFIG,
            },
        ],
    )
    .await;
    let mut journal = Journal::default();

    let mut client = login(running.address, PLAYER).await;
    wait_for_ready(&mut running.log).await;

    // The site, the walk to it and the spawn. A cell whose chunk the teleport has
    // not published yet answers `unloaded`, which is the one refusal this driver
    // retries; a cell the world cannot stand a body on is refused `blocked`, and
    // the fixture moves to the next free home point of interest it listed.
    let mut handle = None;
    let mut entity = None;
    let mut attempts = 0_usize;
    while handle.is_none() {
        let listed = action(&mut client, &mut running.log, &mut journal, "site").await;
        assert!(
            !listed.contains("exhausted"),
            "no authored site's free home point of interest was reservable: {listed}"
        );
        let candidates = parse_field(&listed, "candidates=");
        let walked = action(&mut client, &mut running.log, &mut journal, "goto").await;
        assert!(
            walked.starts_with(&format!("{MARKER}goto committed at ")),
            "the teleport to the reserved cell is what loads it: {walked}"
        );
        let site_chunk = goto_chunk(&walked);
        let mut retries = 0_usize;
        loop {
            let marker = action(&mut client, &mut running.log, &mut journal, "spawn").await;
            if !marker.starts_with(&format!("{MARKER}spawn refused ")) {
                let rest = marker
                    .strip_prefix(&format!("{MARKER}spawn "))
                    .expect("spawn marker");
                let mut words = rest.split_whitespace();
                handle = words.next().map(str::to_owned);
                entity = words.next().map(str::to_owned);
                assert_eq!(
                    words.next(),
                    Some("alive-loaded"),
                    "the spawned resident must be alive and loaded at its cell: {marker}"
                );
                assert!(
                    marker.contains("revision="),
                    "the spawn must answer the resident's own revision: {marker}"
                );
                break;
            }
            assert!(
                marker.starts_with(&format!("{MARKER}spawn refused ")),
                "the fixture answered something else for a spawn: {marker}"
            );
            if marker.ends_with("unloaded") && retries < UNLOADED_RETRIES {
                retries += 1;
                await_chunk(
                    &mut client,
                    &mut running.log,
                    &mut journal,
                    site_chunk,
                    "spawn",
                )
                .await;
                continue;
            }
            break;
        }
        if handle.is_none() {
            attempts += 1;
            assert!(
                attempts <= candidates,
                "none of the {candidates} listed home points of interest materialised a resident"
            );
        }
    }
    let handle = handle.expect("a resident handle");
    assert!(!handle.is_empty(), "the spawn must answer a handle");
    let entity = entity.expect("the spawned resident's entity uuid");
    assert!(
        !entity.is_empty(),
        "the spawn must answer the villager's own entity uuid"
    );

    // The binding at the revision the spawn answered, the same binding one revision
    // earlier, and the binding the refusal left possible.
    let bound = action(&mut client, &mut running.log, &mut journal, "pois").await;
    assert_eq!(
        bound,
        format!(
            "{MARKER}pois {HOME_POI}:{WORK_POI}:{MEETING_POI} revision={}",
            parse_revision(&bound)
        )
    );
    let first_binding = parse_revision(&bound);
    let stale = action(&mut client, &mut running.log, &mut journal, "stale-pois").await;
    assert_eq!(stale, format!("{MARKER}stale-pois refused stale-revision"));
    let rebound = action(
        &mut client,
        &mut running.log,
        &mut journal,
        &format!("pois {SECOND_HOME_POI} {ABSENT} {SECOND_MEETING_POI}"),
    )
    .await;
    assert_eq!(
        rebound,
        format!(
            "{MARKER}pois {SECOND_HOME_POI}:{ABSENT}:{SECOND_MEETING_POI} revision={}",
            parse_revision(&rebound)
        ),
        "a refused binding must leave the revision it read untouched"
    );
    assert!(
        parse_revision(&rebound) > first_binding,
        "the committed binding must be the one that moved the resident's revision"
    );

    // The claim family: the owner claims the very villager its own spawn
    // materialised, by that entity's own uuid and at the revision the committed
    // binding answered - the only revision the resident's own record accepts for an
    // entity this plugin already holds - and the entity claimed at the revision
    // that preceded the binding is refused with nothing written.
    let claimed = action(&mut client, &mut running.log, &mut journal, "claim").await;
    assert_eq!(
        claimed,
        format!(
            "{MARKER}claim {handle} {entity} alive-loaded revision={}",
            parse_revision(&claimed)
        ),
        "the claim must answer the resident this plugin holds for the entity its spawn materialised"
    );
    let stale_claim = action(&mut client, &mut running.log, &mut journal, "stale-claim").await;
    assert_eq!(
        stale_claim,
        format!("{MARKER}stale-claim refused stale-revision"),
        "a claim at the revision that preceded the committed binding must be refused"
    );

    // The work family: nothing to move, the real withdrawal, the committed haul,
    // a revision that already moved, and the cancellation.
    let nothing = action(&mut client, &mut running.log, &mut journal, "missing-work").await;
    assert_eq!(
        nothing,
        format!(
            "{MARKER}missing-work paused reason=missing-input units=0/1 changes={ABSENT} revision={}",
            parse_revision(&nothing)
        ),
        "a worker holding nothing must pause with missing_input and report no change"
    );
    let withdrawn = action(&mut client, &mut running.log, &mut journal, "withdraw").await;
    assert_eq!(
        withdrawn,
        format!(
            "{MARKER}withdraw moved=1 endpoints=2 revision={}",
            parse_revision(&withdrawn)
        )
    );
    // The withdrawal removed the pause cause, so core's own resumption
    // already performed the haul before this explicit assignment: the
    // assignment answers with the finished watermark and no new change.
    let hauled = action(&mut client, &mut running.log, &mut journal, "work").await;
    assert_eq!(
        hauled,
        format!(
            "{MARKER}work committed reason={ABSENT} units=1/1 changes={ABSENT} revision={}",
            parse_revision(&hauled)
        ),
        "the explicit assignment replays the resumption's finished watermark"
    );
    let work_revision = parse_revision(&hauled);
    let stale_work = action(&mut client, &mut running.log, &mut journal, "stale-work").await;
    assert_eq!(
        stale_work,
        format!("{MARKER}stale-work refused stale-revision")
    );
    let cancelled = action(&mut client, &mut running.log, &mut journal, "cancel-work").await;
    assert_eq!(
        cancelled,
        format!(
            "{MARKER}cancel-work {handle} revision={}",
            parse_revision(&cancelled)
        )
    );
    assert!(
        parse_revision(&cancelled) > work_revision,
        "a cancellation is its own durable decision"
    );

    // The order family: the follow order, the batch refusal a stale member revision
    // answers with, and the cancellation.
    let ordered = action(&mut client, &mut running.log, &mut journal, "order").await;
    assert!(
        ordered.starts_with(&format!("{MARKER}order order-revision=")),
        "the order must answer its own order revision: {ordered}"
    );
    assert!(
        ordered.contains("state=applied") && !ordered.contains("slot=none"),
        "a follow order for a live actor must be applied with a formation slot: {ordered}"
    );
    let refused = action(&mut client, &mut running.log, &mut journal, "stale-order").await;
    assert_eq!(
        refused,
        format!("{MARKER}stale-order blocked state=stale-revision members=1"),
        "a batch the owner refuses must still name every member"
    );
    let uncancelled = action(&mut client, &mut running.log, &mut journal, "cancel-order").await;
    assert!(
        uncancelled.starts_with(&format!("{MARKER}cancel-order order-revision=")),
        "the cancellation must answer the order revision it cleared: {uncancelled}"
    );
    assert!(
        uncancelled.contains("state=applied"),
        "a cancellation reports its member as accepted: {uncancelled}"
    );

    // The observer asks for this resident in all four shapes. None of them is its
    // to change, and the owner's own resident still binds afterwards at the
    // revision this test holds, which is what makes the refusals mean nothing was
    // written.
    let foreign_pois = fence(&mut client, &mut running.log, &mut journal, &handle, "pois").await;
    assert_eq!(
        foreign_pois,
        format!("{MARKER}foreign-pois refused forbidden")
    );
    let foreign_claim = fence_claim(&mut client, &mut running.log, &mut journal, &entity, 0).await;
    assert_eq!(
        foreign_claim,
        format!("{MARKER}foreign-claim refused forbidden"),
        "a new claim must not adopt another plugin's resident"
    );
    let foreign_work = fence(&mut client, &mut running.log, &mut journal, &handle, "work").await;
    assert_eq!(
        foreign_work,
        format!("{MARKER}foreign-work refused not-found")
    );
    let foreign_order = fence(
        &mut client,
        &mut running.log,
        &mut journal,
        &handle,
        "order",
    )
    .await;
    assert_eq!(
        foreign_order,
        format!("{MARKER}foreign-order refused blocked members=1 state=stale-revision")
    );
    let rebound = action(&mut client, &mut running.log, &mut journal, "pois").await;
    assert_eq!(
        rebound,
        format!(
            "{MARKER}pois {HOME_POI}:{WORK_POI}:{MEETING_POI} revision={}",
            parse_revision(&rebound)
        ),
        "every refusal this run made must leave the revision this plugin holds"
    );

    // The gear the worker hauled is still on its canonical slot, and the
    // demobilisation keeps the handle and every item.
    let gear = action(&mut client, &mut running.log, &mut journal, "gear").await;
    assert_eq!(
        gear,
        format!(
            "{MARKER}gear {EMERALD_ITEM}:1 revision={}",
            parse_revision(&gear)
        ),
        "the hauled emerald must be in the worker's equipment"
    );
    let demobilized = action(&mut client, &mut running.log, &mut journal, "demobilize").await;
    assert_eq!(
        demobilized,
        format!(
            "{MARKER}demobilize {handle} demobilizing reason=no-storage returned=0 revision={}",
            parse_revision(&demobilized)
        ),
        "a demobilisation with nowhere to hand its gear keeps the handle and the gear"
    );
    let kept = action(&mut client, &mut running.log, &mut journal, "gear").await;
    assert_eq!(
        kept,
        format!(
            "{MARKER}gear {EMERALD_ITEM}:1 revision={}",
            parse_revision(&kept)
        ),
        "demobilising must not lose the worker's gear"
    );

    // The durable side: the server's own save path, then the world's file, which is
    // the state no client observed.
    let report = running.save.save_all().await;
    assert!(report.is_ok(), "the save path failed: {report:?}");
    drop(client);
    let errors = error_lines(running.stop().await);
    assert!(
        errors.is_empty(),
        "the fixture reported a step it could not conclude: {errors:?}"
    );
    let saved = saved_inventory(world.path());
    assert_eq!(
        saved_total(&saved, EMERALD_ITEM),
        SEED_EMERALDS - 1,
        "the withdrawal really moved one emerald out of the player's own inventory"
    );
}

/// The capability boundary: the very resident record the fixture sends converts
/// under a manifest that declares `persistent_residents`, and is refused by *name*
/// under one that does not.
#[test]
fn a_resident_command_without_its_grant_is_refused_by_name() {
    let limits = PluginLimits::default();
    let mut batch = CommandBatch::new();
    batch
        .push(resident_command(), &limits)
        .expect("the record stages");
    assert_eq!(
        to_script_batch(
            batch,
            batch_limit(),
            &NoSessions,
            &CommandCapabilities::none()
        ),
        Err(AdapterError::PermissionDenied {
            capability: "persistent_residents"
        }),
        "the refusal names the capability the manifest would have declared"
    );

    // The control: the same record converts under the grant, so the refusal above is
    // the capability's and not a record this test got wrong.
    let mut batch = CommandBatch::new();
    batch
        .push(resident_command(), &limits)
        .expect("the record stages");
    let converted = to_script_batch(
        batch,
        batch_limit(),
        &NoSessions,
        &granted_resident_capabilities(),
    )
    .expect("the fixture's own claim converts");
    let [mc_script::ScriptCommand::Operation { request }] = converted.commands() else {
        panic!("expected one operation, saw {:?}", converted.commands());
    };
    assert_eq!(request.request_id(), CLAIM_REQUEST);
    assert_eq!(request.operation_id(), Some(CLAIM_OPERATION));
}

/// The request and operation ids the staged claim names: the fixture's own spelling
/// for its claim action, so this case reads back what a guest decided to send.
const CLAIM_REQUEST: &str = "res-claim";
const CLAIM_OPERATION: &str = "res-op-claim";

/// One resident claim record, as the contract's own bindings spell it.
fn resident_command() -> WireCommand {
    WireCommand::Operation(OperationRequest {
        request: CLAIM_REQUEST.to_owned(),
        operation: DomainOperation::Resident(ResidentOperation::Claim(ResidentClaim {
            operation_id: CLAIM_OPERATION.to_owned(),
            actor_id: 7,
            entity_uuid: "1a2b3c4d-5e6f-4a8b-9c0d-1e2f3a4b5c6d".to_owned(),
            expected_entity_revision: 0,
        })),
    })
}

/// The capabilities a manifest that declared the resident capability resolves to,
/// which is what the host pre-checks a callback's answer against.
fn granted_resident_capabilities() -> CommandCapabilities {
    ScriptPluginManifest::new(
        OWNER,
        "Resident Compat",
        "0.1.0",
        mc_script::COMPONENT_PLUGIN_API_VERSION,
    )
    .declare_persistent_residents()
    .validate_for(mc_script::COMPONENT_PLUGIN_API_VERSION)
    .expect("the fixture's own declaration validates")
    .to_command_capabilities()
}

/// The bound every staged batch of the capability case is admitted against.
fn batch_limit() -> NonZeroUsize {
    NonZeroUsize::new(mc_script::MAX_SCRIPT_COMMAND_BATCH).expect("non-zero")
}

/// Log the fixture's player in over a fresh connection and return the client, once
/// the server has published the play entry, the command tree and the position the
/// client acknowledges. Every connection of this test is a real one.
async fn login(address: SocketAddr, name: &str) -> Client {
    let mut client = Client::connect(address).await.expect("client connect");
    let _ = client
        .drive_login(address, name)
        .await
        .expect("drive login");
    client
        .drive_configuration()
        .await
        .expect("drive configuration");
    let _ = client.read_play_login().await.expect("play entry");
    let _: ClientboundCommands = client.read_typed().await.expect("Commands");
    let sync: SynchronizePlayerPosition =
        client.read_typed().await.expect("initial player position");
    client
        .write_packet(&ConfirmTeleportation {
            teleport_id: sync.teleport_id,
        })
        .await
        .expect("confirm initial position");
    client
        .write_packet(&ServerboundPlayerLoaded)
        .await
        .expect("report the player loaded");
    client
}

/// Wait for the fixture's own readiness line, which is what a driver waits for
/// before it sends the first action.
async fn wait_for_ready(log: &mut UnboundedReceiver<LogLine>) {
    let deadline = tokio::time::Instant::now() + WIRE_TIMEOUT;
    loop {
        let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
        let line = tokio::time::timeout(remaining, log.recv())
            .await
            .unwrap_or_else(|_| panic!("the fixture never logged {READY:?}"));
        let Some(line) = line else {
            panic!("the component host left before the fixture logged {READY:?}");
        };
        assert!(
            !line.error,
            "{} reported an error before it logged {READY:?}: {}",
            line.plugin, line.message
        );
        if line.message == READY {
            return;
        }
    }
}

/// Send one `resident` action and answer the line the fixture reported for it.
///
/// The wait ends on a line the fixture produced, never on a sleep: a marker that
/// never arrives is the step stalling, and an error line - which the fixture logs
/// instead of a marker - is the most specific failure this test can report. Every
/// chat line read while waiting is kept, so a later assertion can still see what an
/// earlier step did not wait for.
async fn action(
    client: &mut Client,
    log: &mut UnboundedReceiver<LogLine>,
    journal: &mut Journal,
    arguments: &str,
) -> String {
    let name = arguments.split_whitespace().next().unwrap_or(arguments);
    client
        .write_packet(&ServerboundChatCommand {
            command: format!("resident {arguments}"),
        })
        .await
        .unwrap_or_else(|error| panic!("send /resident {arguments}: {error}"));
    expect(client, log, journal, &format!("{MARKER}{name} "), arguments).await
}

/// Send one `resident-fence` request for another plugin's handle and answer the
/// line the observer reported.
async fn fence(
    client: &mut Client,
    log: &mut UnboundedReceiver<LogLine>,
    journal: &mut Journal,
    handle: &str,
    shape: &str,
) -> String {
    client
        .write_packet(&ServerboundChatCommand {
            command: format!("resident-fence {handle} {shape}"),
        })
        .await
        .unwrap_or_else(|error| panic!("send /resident-fence {handle} {shape}: {error}"));
    expect(
        client,
        log,
        journal,
        &format!("{MARKER}foreign-{shape} "),
        &format!("fence {shape}"),
    )
    .await
}

/// Attempt to adopt another plugin's entity with the new-claim revision.
async fn fence_claim(
    client: &mut Client,
    log: &mut UnboundedReceiver<LogLine>,
    journal: &mut Journal,
    entity: &str,
    revision: u64,
) -> String {
    client
        .write_packet(&ServerboundChatCommand {
            command: format!("resident-fence {entity} claim {revision}"),
        })
        .await
        .unwrap_or_else(|error| panic!("send /resident-fence {entity} claim {revision}: {error}"));
    expect(
        client,
        log,
        journal,
        &format!("{MARKER}foreign-claim "),
        "fence claim",
    )
    .await
}

/// Read until the line one step is expected to report has arrived.
async fn expect(
    client: &mut Client,
    log: &mut UnboundedReceiver<LogLine>,
    journal: &mut Journal,
    expected: &str,
    step: &str,
) -> String {
    let deadline = tokio::time::Instant::now() + ACTION_TIMEOUT;
    loop {
        let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
        if remaining.is_zero() {
            panic!(
                "the {step} step never reported a line; saw {:?}",
                journal.chats
            );
        }
        if let Some(offset) = journal.chats[journal.next_reply..]
            .iter()
            .position(|text| text.starts_with(expected))
        {
            journal.next_reply += offset + 1;
            return journal.chats[journal.next_reply - 1].clone();
        }
        tokio::select! {
            line = log.recv() => {
                let Some(line) = line else {
                    panic!("the component host left before the {step} step reported a line");
                };
                assert!(
                    !line.error,
                    "{} reported a plugin error instead of the {step} step reporting a line: {}",
                    line.plugin,
                    line.message
                );
            }
            frame = tokio::time::timeout(remaining, client.read_frame()) => {
                let mut frame = match frame {
                    Ok(Ok(frame)) => frame,
                    Ok(Err(error)) => panic!("the {step} step lost its connection: {error}"),
                    Err(_) => panic!(
                        "the {step} step never reported a line; saw {:?}",
                        journal.chats
                    ),
                };
                if frame.id == ClientboundSystemChat::ID {
                    record_chat(journal, &mut frame.body);
                } else if frame.id == SynchronizePlayerPosition::ID {
                    let sync = SynchronizePlayerPosition::decode(&mut frame.body)
                        .expect("decode teleport");
                    client.write_packet(&ConfirmTeleportation {
                        teleport_id: sync.teleport_id,
                    }).await.expect("confirm teleport");
                } else if frame.id == LevelChunkWithLight::ID {
                    let chunk = LevelChunkWithLight::decode(&mut frame.body)
                        .expect("decode chunk");
                    journal.chunks.insert((chunk.chunk_x, chunk.chunk_z));
                } else if frame.id == ClientboundKeepAlive::ID {
                    let keepalive = ClientboundKeepAlive::decode(&mut frame.body)
                        .expect("decode keepalive");
                    client.write_packet(&ServerboundKeepAlive {
                        id: keepalive.id,
                    }).await.expect("answer keepalive");
                }
            }
        }
    }
}

/// Wait until the client holds the one chunk a refused spawn needs.
///
/// A spawn at a cell the teleport has not published yet is refused `unloaded`,
/// and retrying without waiting races the chunk's own load: eight fast refusals
/// spend the retries before a slow runner's loader converges, and every
/// candidate cell loses the same race. The wait ends on the chunk's own data
/// packet - the publication that lets the spawn succeed - never on a sleep.
async fn await_chunk(
    client: &mut Client,
    log: &mut UnboundedReceiver<LogLine>,
    journal: &mut Journal,
    target: (i32, i32),
    step: &str,
) {
    if journal.chunks.contains(&target) {
        return;
    }
    let deadline = tokio::time::Instant::now() + ACTION_TIMEOUT;
    loop {
        let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
        if remaining.is_zero() {
            panic!(
                "the {step} step never received chunk {target:?}; saw {:?}",
                journal.chats
            );
        }
        tokio::select! {
            line = log.recv() => {
                let Some(line) = line else {
                    panic!(
                        "the component host left before the {step} step received chunk {target:?}"
                    );
                };
                assert!(
                    !line.error,
                    "{} reported a plugin error while the {step} step waited for chunk {target:?}: {}",
                    line.plugin,
                    line.message
                );
            }
            frame = tokio::time::timeout(remaining, client.read_frame()) => {
                let mut frame = match frame {
                    Ok(Ok(frame)) => frame,
                    Ok(Err(error)) => panic!("the {step} step lost its connection: {error}"),
                    Err(_) => panic!(
                        "the {step} step never received chunk {target:?}; saw {:?}",
                        journal.chats
                    ),
                };
                if frame.id == ClientboundSystemChat::ID {
                    record_chat(journal, &mut frame.body);
                } else if frame.id == LevelChunkWithLight::ID {
                    let chunk = LevelChunkWithLight::decode(&mut frame.body)
                        .expect("decode chunk");
                    let coords = (chunk.chunk_x, chunk.chunk_z);
                    journal.chunks.insert(coords);
                    if coords == target {
                        return;
                    }
                } else if frame.id == SynchronizePlayerPosition::ID {
                    let sync = SynchronizePlayerPosition::decode(&mut frame.body)
                        .expect("decode teleport");
                    client.write_packet(&ConfirmTeleportation {
                        teleport_id: sync.teleport_id,
                    }).await.expect("confirm teleport");
                } else if frame.id == ClientboundKeepAlive::ID {
                    let keepalive = ClientboundKeepAlive::decode(&mut frame.body)
                        .expect("decode keepalive");
                    client.write_packet(&ServerboundKeepAlive {
                        id: keepalive.id,
                    }).await.expect("answer keepalive");
                }
            }
        }
    }
}

/// The chunk coordinates of the cell one committed `goto` names.
///
/// The marker reports the teleport's position as `x/y/z`; the chunk a spawn at
/// that cell needs is the one holding its floor.
fn goto_chunk(line: &str) -> (i32, i32) {
    let position = line.split(" at ").nth(1).expect("the goto position");
    let mut coordinates = position.split('/');
    let x = coordinates
        .next()
        .expect("the goto x")
        .parse::<f64>()
        .expect("the goto x");
    let z = coordinates
        .nth(1)
        .expect("the goto z")
        .parse::<f64>()
        .expect("the goto z");
    ((x.floor() as i32) >> 4, (z.floor() as i32) >> 4)
}

/// Record one system chat frame's literal text.
///
/// The fixture reports a step it could not conclude by logging, not by chatting, so
/// every line here is a marker this run produced.
fn record_chat(journal: &mut Journal, body: &mut Bytes) {
    let chat = ClientboundSystemChat::decode(body).expect("decode system chat");
    let text = literal_text_component_text(&chat.content_nbt);
    assert!(
        !text.starts_with(UNEXPECTED),
        "the fixture could not conclude a step: {text}"
    );
    journal.chats.push(text);
}

/// The revision one marker names.
fn parse_revision(line: &str) -> u64 {
    line.split_whitespace()
        .find_map(|word| word.strip_prefix("revision="))
        .and_then(|value| value.parse().ok())
        .unwrap_or_else(|| panic!("no revision in {line:?}"))
}

/// One `name=value` field of one marker.
fn parse_field(line: &str, name: &str) -> usize {
    line.split_whitespace()
        .find_map(|word| word.strip_prefix(name))
        .and_then(|value| value.parse().ok())
        .unwrap_or_else(|| panic!("no {name} in {line:?}"))
}

/// The error lines one run's guests logged, as a test reports them: a guest that
/// could not conclude a step logs one instead of a marker, so a run with any of
/// them did not finish the sequence it was asked for.
fn error_lines(lines: Vec<LogLine>) -> Vec<String> {
    lines
        .into_iter()
        .filter(|line| line.error)
        .map(|line| format!("{}: {}", line.plugin, line.message))
        .collect()
}

/// The authored catalog of the settlement profile this run deploys: four buildable
/// blueprints, one per role the owner requires, in the format core's own catalog
/// reader validates.
///
/// The home blueprint's point of interest sits on the column the building is
/// grounded on (`[0, 1, 0]` of its own footprint), which is what lets the owner
/// stand a body on the terrain's own surface row instead of on a spot that may be
/// buried or hanging. Its capacity covers every inhabitant slot a candidate can
/// pick.
fn write_catalog(root: &Path) {
    let structures = root.join("structures");
    std::fs::create_dir_all(&structures).expect("catalog directory");
    for (file, text) in [
        ("house_small.toml", blueprint("house_small", "home", 64)),
        ("town_hall.toml", blueprint("town_hall", "meeting", 0)),
        ("smithy.toml", blueprint("smithy", "work", 0)),
        ("watch_post.toml", blueprint("watch_post", "guard", 0)),
    ] {
        std::fs::write(structures.join(file), text).expect("blueprint file");
    }
}

/// One authored blueprint: a four-by-four footprint with a stone foundation and a
/// plank body, one point of interest of `kind` on its own anchor column, and one
/// stage that lays its body.
fn blueprint(name: &str, kind: &str, capacity: u16) -> String {
    format!(
        "id = \"{CATALOG_NAMESPACE}:{name}\"\nrevision = 1\n\
         [footprint]\nsize = [4, 4, 4]\nanchor = [0, 0, 0]\n\
         [[palette]]\nindex = 0\nblock = \"minecraft:stone\"\nproperties = {{}}\n\
         [[palette]]\nindex = 1\nblock = \"minecraft:oak_planks\"\nproperties = {{}}\n\
         [[blocks]]\nx = 0\ny = 0\nz = 0\npalette = 0\n\
         [[poi]]\nid = \"{kind}\"\nkind = \"{kind}\"\nat = [0, 1, 0]\ncapacity = {capacity}\n\
         [[street_connection]]\nat = [0, 0, 0]\nfacing = \"north\"\n\
         [[stage]]\nid = \"body\"\n\
         [[stage.blocks]]\nx = 0\ny = 1\nz = 0\npalette = 1\n"
    )
}

/// The player state the world's own durable format holds for `PLAYER`, written
/// before the server opens the world.
///
/// This is the server's canonical player format - gzip of the named NBT the server
/// itself reads on login - so the emeralds are state the server validates on load,
/// not a value this test hands the guest.
fn seed_player_state(world_dir: &Path) {
    let uuid = mc_net::offline_uuid(PLAYER);
    let path = world_dir.join("playerdata").join(format!("{uuid}.dat"));
    std::fs::create_dir_all(path.parent().expect("playerdata directory"))
        .expect("playerdata directory");
    let root = Tag::Compound(vec![(
        "Inventory".to_owned(),
        Tag::List(mc_nbt::ListTag {
            element_type: mc_nbt::tag_type::COMPOUND,
            elements: vec![Tag::Compound(vec![
                ("Slot".to_owned(), Tag::Byte(EMERALD_SLOT as i8)),
                ("id".to_owned(), Tag::String(EMERALD_ITEM.to_owned())),
                ("count".to_owned(), Tag::Int(SEED_EMERALDS)),
            ])],
        }),
    )]);
    let mut encoded = Vec::new();
    mc_nbt::write_named(&mut encoded, "", &root).expect("the player state encodes");
    let file = std::fs::File::create(&path).expect("player data file");
    let mut encoder = flate2::write::GzEncoder::new(file, flate2::Compression::default());
    encoder.write_all(&encoded).expect("write the player state");
    encoder.finish().expect("finish the player state");
}

/// The inventory the world's own player file holds for `PLAYER`, as the entries
/// the server wrote.
fn saved_inventory(world_dir: &Path) -> Vec<Vec<(String, Tag)>> {
    let path = world_dir
        .join("playerdata")
        .join(format!("{}.dat", mc_net::offline_uuid(PLAYER)));
    let file = std::fs::File::open(&path).unwrap_or_else(|error| {
        panic!(
            "the save path left no player state at {}: {error}",
            path.display()
        )
    });
    let mut decoded = Vec::new();
    flate2::read::GzDecoder::new(file)
        .read_to_end(&mut decoded)
        .expect("decompress the player state");
    let mut slice = decoded.as_slice();
    let (_, root) = mc_nbt::read_named(&mut slice).expect("read the player state");
    let Tag::Compound(fields) = root else {
        panic!("the saved player state root must be a compound");
    };
    let inventory = fields
        .into_iter()
        .find_map(|(name, tag)| (name == "Inventory").then_some(tag));
    let Some(Tag::List(list)) = inventory else {
        panic!("the saved player state holds no inventory list");
    };
    list.elements
        .into_iter()
        .filter_map(|element| match element {
            Tag::Compound(item) => Some(item),
            _ => None,
        })
        .collect()
}

/// How many items of one resource the saved inventory entries hold.
fn saved_total(entries: &[Vec<(String, Tag)>], resource: &str) -> i32 {
    entries
        .iter()
        .filter(|fields| {
            fields
                .iter()
                .find(|(name, _)| name == "id")
                .is_some_and(|(_, tag)| matches!(tag, Tag::String(text) if text == resource))
        })
        .map(|fields| {
            fields
                .iter()
                .find(|(name, _)| name == "count")
                .map_or(0, |(_, tag)| match tag {
                    Tag::Int(value) => *value,
                    _ => 0,
                })
        })
        .sum()
}

/// One persistent world handle, reopened from disk.
fn open_world(
    world_dir: &Path,
    registries: &Registries,
) -> Arc<tokio::sync::Mutex<mc_world::WorldStorage>> {
    let storage =
        mc_world::WorldStorage::open_with_capacity(world_dir, Arc::clone(&registries.blocks), 49)
            .expect("reopen the persistent world")
            .with_item_registry(Arc::clone(&registries.items))
            .with_generator(Arc::new(mc_worldgen::TerrainGenerator::new(
                0,
                Arc::clone(&registries.blocks),
            )));
    Arc::new(tokio::sync::Mutex::new(storage))
}

/// The server configuration every run binds with: one persistent world, so the
/// real resident, settlement and inventory owners are started and their decisions
/// are the ones on disk.
fn server_config(
    registries: &Registries,
    world: Arc<tokio::sync::Mutex<mc_world::WorldStorage>>,
    shutdown: &mc_net::ShutdownHandle,
    motd: &str,
) -> mc_net::ServerConfig {
    mc_net::ServerConfig {
        tab_list: mc_net::TabListConfig::default(),
        bind_address: "127.0.0.1:0".parse().unwrap(),
        motd: motd.to_owned(),
        max_players: 1,
        view_distance: 2,
        data: Arc::clone(&registries.data),
        blocks: Arc::clone(&registries.blocks),
        world: Some(world),
        tags: Arc::clone(&registries.tags),
        recipes: Arc::clone(&registries.recipes),
        loot: Arc::clone(&registries.loot),
        block_light: None,
        items: Arc::clone(&registries.items),
        item_facts: Arc::clone(&registries.item_facts),
        block_facts: Arc::clone(&registries.block_facts),
        entity_types: Arc::clone(&registries.entity_types),
        biome_spawns: Arc::new(mc_data::biomes::BiomeSpawnRules::default()),
        chunk_pipeline: mc_net::ChunkPipelinePolicy::default(),
        random_tick: mc_net::RandomTickPolicy::default(),
        command_permissions: mc_net::CommandPermissionConfig::new(Vec::<String>::new(), true),
        loader_manifest: None,
        shutdown: shutdown.clone(),
    }
}

/// The literal text of one system-chat frame, as the server's own component
/// encodes it.
fn literal_text_component_text(component: &[u8]) -> String {
    let mut bytes = Bytes::copy_from_slice(component);
    let tag = mc_nbt::read_network(&mut bytes).expect("read text component nbt");
    let Tag::Compound(fields) = tag else {
        panic!("system chat component root must be a compound");
    };
    fields
        .into_iter()
        .find_map(|(name, tag)| match (name.as_str(), tag) {
            ("text", Tag::String(text)) => Some(text),
            _ => None,
        })
        .expect("literal system chat text")
}
