#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT"

export SOLARIS_ENTITY_BENCH_MODE="${SOLARIS_ENTITY_BENCH_MODE:-baseline}"
export SOLARIS_ENTITY_BENCH_OUT_DIR="${SOLARIS_ENTITY_BENCH_OUT_DIR:-.analysis/bench/living-world-100k}"
export SOLARIS_ENTITY_BENCH_CLIENTS="${SOLARIS_ENTITY_BENCH_CLIENTS:-50}"
export SOLARIS_ENTITY_BENCH_REGIONS="${SOLARIS_ENTITY_BENCH_REGIONS:-25}"
export SOLARIS_ENTITY_BENCH_ENTITIES_PER_REGION="${SOLARIS_ENTITY_BENCH_ENTITIES_PER_REGION:-4000}"
export SOLARIS_ENTITY_BENCH_ENTITY_MIX="${SOLARIS_ENTITY_BENCH_ENTITY_MIX:-minecraft:villager=40000,minecraft:cow=12000,minecraft:sheep=12000,minecraft:pig=12000,minecraft:chicken=12000,minecraft:rabbit=12000}"
export SOLARIS_ENTITY_BENCH_VIEW_DISTANCE="${SOLARIS_ENTITY_BENCH_VIEW_DISTANCE:-6}"
export SOLARIS_ENTITY_BENCH_REGION_SPACING_BLOCKS="${SOLARIS_ENTITY_BENCH_REGION_SPACING_BLOCKS:-2048}"
export SOLARIS_ENTITY_BENCH_WARMUP_TICKS="${SOLARIS_ENTITY_BENCH_WARMUP_TICKS:-200}"
export SOLARIS_ENTITY_BENCH_MEASURE_TICKS="${SOLARIS_ENTITY_BENCH_MEASURE_TICKS:-1200}"
export SOLARIS_ENTITY_BENCH_READINESS_TIMEOUT_SECS="${SOLARIS_ENTITY_BENCH_READINESS_TIMEOUT_SECS:-600}"
export SOLARIS_ENTITY_BENCH_P95_BUDGET_US="${SOLARIS_ENTITY_BENCH_P95_BUDGET_US:-50000}"
export SOLARIS_ENTITY_BENCH_P99_BUDGET_US="${SOLARIS_ENTITY_BENCH_P99_BUDGET_US:-60000}"
export SOLARIS_ENTITY_BENCH_CONNECT_WAVE="${SOLARIS_ENTITY_BENCH_CONNECT_WAVE:-4}"
export SOLARIS_ENTITY_BENCH_LOG_FILTER="${SOLARIS_ENTITY_BENCH_LOG_FILTER:-mc_net::lock_metrics=error,mc_net::server=warn}"

exec "$ROOT/tools/harness/backends/entity_scale.sh"
