//! Mob-effect registry identities from the local vanilla 26.1.2 registry report.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum MobEffect {
    Speed = 0,
    Slowness = 1,
    Haste = 2,
    MiningFatigue = 3,
    Strength = 4,
    InstantHealth = 5,
    InstantDamage = 6,
    JumpBoost = 7,
    Nausea = 8,
    Regeneration = 9,
    Resistance = 10,
    FireResistance = 11,
    WaterBreathing = 12,
    Invisibility = 13,
    Blindness = 14,
    NightVision = 15,
    Hunger = 16,
    Weakness = 17,
    Poison = 18,
    Wither = 19,
    HealthBoost = 20,
    Absorption = 21,
    Saturation = 22,
    Glowing = 23,
    Levitation = 24,
    Luck = 25,
    Unluck = 26,
    SlowFalling = 27,
    ConduitPower = 28,
    DolphinsGrace = 29,
    BadOmen = 30,
    HeroOfTheVillage = 31,
    Darkness = 32,
    TrialOmen = 33,
    RaidOmen = 34,
    WindCharged = 35,
    Weaving = 36,
    Oozing = 37,
    Infested = 38,
    BreathOfTheNautilus = 39,
}

impl MobEffect {
    #[must_use]
    pub fn from_name(name: &str) -> Option<Self> {
        Some(match name {
            "minecraft:speed" => Self::Speed,
            "minecraft:slowness" => Self::Slowness,
            "minecraft:haste" => Self::Haste,
            "minecraft:mining_fatigue" => Self::MiningFatigue,
            "minecraft:strength" => Self::Strength,
            "minecraft:instant_health" => Self::InstantHealth,
            "minecraft:instant_damage" => Self::InstantDamage,
            "minecraft:jump_boost" => Self::JumpBoost,
            "minecraft:nausea" => Self::Nausea,
            "minecraft:regeneration" => Self::Regeneration,
            "minecraft:resistance" => Self::Resistance,
            "minecraft:fire_resistance" => Self::FireResistance,
            "minecraft:water_breathing" => Self::WaterBreathing,
            "minecraft:invisibility" => Self::Invisibility,
            "minecraft:blindness" => Self::Blindness,
            "minecraft:night_vision" => Self::NightVision,
            "minecraft:hunger" => Self::Hunger,
            "minecraft:weakness" => Self::Weakness,
            "minecraft:poison" => Self::Poison,
            "minecraft:wither" => Self::Wither,
            "minecraft:health_boost" => Self::HealthBoost,
            "minecraft:absorption" => Self::Absorption,
            "minecraft:saturation" => Self::Saturation,
            "minecraft:glowing" => Self::Glowing,
            "minecraft:levitation" => Self::Levitation,
            "minecraft:luck" => Self::Luck,
            "minecraft:unluck" => Self::Unluck,
            "minecraft:slow_falling" => Self::SlowFalling,
            "minecraft:conduit_power" => Self::ConduitPower,
            "minecraft:dolphins_grace" => Self::DolphinsGrace,
            "minecraft:bad_omen" => Self::BadOmen,
            "minecraft:hero_of_the_village" => Self::HeroOfTheVillage,
            "minecraft:darkness" => Self::Darkness,
            "minecraft:trial_omen" => Self::TrialOmen,
            "minecraft:raid_omen" => Self::RaidOmen,
            "minecraft:wind_charged" => Self::WindCharged,
            "minecraft:weaving" => Self::Weaving,
            "minecraft:oozing" => Self::Oozing,
            "minecraft:infested" => Self::Infested,
            "minecraft:breath_of_the_nautilus" => Self::BreathOfTheNautilus,
            _ => return None,
        })
    }
}

#[must_use]
pub fn name_for_id(id: u32) -> Option<&'static str> {
    const NAMES: [&str; 40] = [
        "minecraft:speed",
        "minecraft:slowness",
        "minecraft:haste",
        "minecraft:mining_fatigue",
        "minecraft:strength",
        "minecraft:instant_health",
        "minecraft:instant_damage",
        "minecraft:jump_boost",
        "minecraft:nausea",
        "minecraft:regeneration",
        "minecraft:resistance",
        "minecraft:fire_resistance",
        "minecraft:water_breathing",
        "minecraft:invisibility",
        "minecraft:blindness",
        "minecraft:night_vision",
        "minecraft:hunger",
        "minecraft:weakness",
        "minecraft:poison",
        "minecraft:wither",
        "minecraft:health_boost",
        "minecraft:absorption",
        "minecraft:saturation",
        "minecraft:glowing",
        "minecraft:levitation",
        "minecraft:luck",
        "minecraft:unluck",
        "minecraft:slow_falling",
        "minecraft:conduit_power",
        "minecraft:dolphins_grace",
        "minecraft:bad_omen",
        "minecraft:hero_of_the_village",
        "minecraft:darkness",
        "minecraft:trial_omen",
        "minecraft:raid_omen",
        "minecraft:wind_charged",
        "minecraft:weaving",
        "minecraft:oozing",
        "minecraft:infested",
        "minecraft:breath_of_the_nautilus",
    ];
    NAMES.get(id as usize).copied()
}
