#!/usr/bin/env bash
# Extract the vanilla 26.1.x data files Solaris depends on (per ADR 0001)
# out of the bundled Mojang server jar.
#
# Usage:
#   tools/extract-vanilla-data.sh [path/to/server.jar]
#
# Default source: .analysis/server.jar (the bundle JAR — this script
# walks past the bundler layer to the embedded version-specific jar).
#
# Output: populates data/vanilla/ with a tracked subset:
#   - All top-level registry directories that the Configuration state's
#     Registry Data packet covers (dimension_type, damage_type, …).
#   - worldgen data used by generation (biomes, features, structures,
#     template pools, processors).
#   - tags/ (for the UpdateTags packet, M2+).
#   - recipe/ and loot_table/ (for data-driven survival item/recipe/loot
#     foundations, M25+).
#   - reports/minecraft/components/item/ generated by the server's own
#     Default Components provider (M25+ item facts).
#   - version.json (for sanity-pinning).
#   - reports/{blocks,registries,packets}.json generated by the server's
#     own data generator (`--reports`). blocks.json is the canonical
#     block-state-id mapping mc-world depends on in M2.
#
# Re-runnable; safe to delete data/vanilla/ first if you want a clean slate.
#
# Requires Java matching the server's java_version (25 for 26.1.x). Override
# with `JAVA=...`; defaults to the sdkman 25.0.2-graalce install used by
# dump-vanilla-protocol.sh.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUNDLE_JAR="${1:-$REPO_ROOT/.analysis/server.jar}"
OUT_DIR="$REPO_ROOT/data/vanilla"
JAVA="${JAVA:-/home/user/.sdkman/candidates/java/25.0.2-graalce/bin/java}"

if [[ ! -f "$BUNDLE_JAR" ]]; then
  echo "error: bundle jar not found at $BUNDLE_JAR" >&2
  exit 1
fi
if [[ ! -x "$JAVA" ]]; then
  echo "error: java not found at $JAVA (override with JAVA=…)" >&2
  exit 1
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "[1/5] Unpacking bundle JAR…"
mkdir -p "$TMP/bundle"
unzip -q -o "$BUNDLE_JAR" -d "$TMP/bundle"

INNER_JAR="$(find "$TMP/bundle/META-INF/versions" -name 'server-*.jar' | head -n1)"
if [[ -z "$INNER_JAR" ]]; then
  echo "error: could not locate inner server-<version>.jar inside the bundle" >&2
  exit 1
fi
echo "    inner jar: $(basename "$INNER_JAR")"

echo "[2/5] Reading version metadata…"
unzip -p "$BUNDLE_JAR" version.json > "$TMP/version.json"
VERSION_ID="$(grep -m1 '"id"' "$TMP/version.json" | sed 's/.*"id": *"\([^"]*\)".*/\1/')"
PROTOCOL="$(grep -m1 '"protocol_version"' "$TMP/version.json" | sed 's/.*: *\([0-9]*\).*/\1/')"
echo "    version=$VERSION_ID protocol=$PROTOCOL"

echo "[3/5] Extracting data subset to $OUT_DIR …"
# Wipe only generated subdirs/files. README and any other tracked files
# (schema notes, ADR pointers) stay in place.
rm -rf "$OUT_DIR/data" "$OUT_DIR/reports" "$OUT_DIR/version.json"
mkdir -p "$OUT_DIR"
cp "$TMP/version.json" "$OUT_DIR/version.json"

# Top-level registry folders we want. Keep this list in sync with the
# registries the Configuration state expects in 26.1.
REGISTRIES=(
  banner_pattern
  cat_sound_variant
  cat_variant
  chat_type
  chicken_sound_variant
  chicken_variant
  cow_sound_variant
  cow_variant
  damage_type
  dialog
  dimension_type
  enchantment
  enchantment_provider
  frog_variant
  instrument
  jukebox_song
  painting_variant
  pig_sound_variant
  pig_variant
  timeline
  trade_set
  trim_material
  trim_pattern
  villager_trade
  wolf_sound_variant
  wolf_variant
  world_clock
  zombie_nautilus_variant
)

mkdir -p "$TMP/extract"
unzip -q -o "$INNER_JAR" 'data/minecraft/*' -d "$TMP/extract"

mkdir -p "$OUT_DIR/data/minecraft"
for reg in "${REGISTRIES[@]}"; do
  if [[ -d "$TMP/extract/data/minecraft/$reg" ]]; then
    cp -r "$TMP/extract/data/minecraft/$reg" "$OUT_DIR/data/minecraft/$reg"
  else
    echo "    warning: registry $reg not found in this version" >&2
  fi
done

WORLDGEN_DIRS=(
  biome
  configured_feature
  placed_feature
  structure
  structure_set
  template_pool
  processor_list
  multi_noise_biome_source_parameter_list
)

mkdir -p "$OUT_DIR/data/minecraft/worldgen"
for dir in "${WORLDGEN_DIRS[@]}"; do
  if [[ -d "$TMP/extract/data/minecraft/worldgen/$dir" ]]; then
    cp -r "$TMP/extract/data/minecraft/worldgen/$dir" "$OUT_DIR/data/minecraft/worldgen/$dir"
  else
    echo "    warning: worldgen/$dir not found in this version" >&2
  fi
done

if [[ -d "$TMP/extract/data/minecraft/structure" ]]; then
  cp -r "$TMP/extract/data/minecraft/structure" "$OUT_DIR/data/minecraft/structure"
fi

cp -r "$TMP/extract/data/minecraft/tags" "$OUT_DIR/data/minecraft/tags"

SURVIVAL_DATA_DIRS=(
  recipe
  loot_table
)

for dir in "${SURVIVAL_DATA_DIRS[@]}"; do
  if [[ -d "$TMP/extract/data/minecraft/$dir" ]]; then
    cp -r "$TMP/extract/data/minecraft/$dir" "$OUT_DIR/data/minecraft/$dir"
  else
    echo "    warning: survival data $dir not found in this version" >&2
  fi
done

echo "[4/5] Generating data reports via server's own data generator …"
mkdir -p "$TMP/datagen"
(
  cd "$TMP/datagen"
  "$JAVA" -DbundlerMainClass=net.minecraft.data.Main \
    -jar "$BUNDLE_JAR" --server --reports >/dev/null 2>&1
)
if [[ ! -f "$TMP/datagen/generated/reports/blocks.json" ]]; then
  echo "error: --reports did not produce blocks.json; rerun with stderr visible to debug" >&2
  exit 1
fi
mkdir -p "$OUT_DIR/reports"
for r in blocks.json registries.json packets.json; do
  cp "$TMP/datagen/generated/reports/$r" "$OUT_DIR/reports/$r"
done
if [[ -d "$TMP/datagen/generated/reports/minecraft/components/item" ]]; then
  mkdir -p "$OUT_DIR/reports/minecraft/components"
  cp -r \
    "$TMP/datagen/generated/reports/minecraft/components/item" \
    "$OUT_DIR/reports/minecraft/components/item"
else
  echo "    warning: default item component reports not generated" >&2
fi

echo "[5/5] Done."
file_count=$(find "$OUT_DIR" -type f | wc -l)
total_bytes=$(du -sb "$OUT_DIR" | awk '{print $1}')
echo "    extracted $file_count files, $total_bytes bytes ($(du -sh "$OUT_DIR" | awk '{print $1}'))"
